$:
  # ===== 开发环境（vscode + docker-in-docker），Cloud Studio 环境声明 =====
  vscode:
    - docker:
        image: docker.cnb.cool/xiaoqianran/java-21-node-22
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls
