const ACTIVE_STATUSES=new Set(['generation-pending','generation-cancelling','connection-required']);
const text=(value,fallback='—')=>value==null||value===''?fallback:String(value);
const clone=(value)=>value==null?value:structuredClone(value);

export const generationJobCenterMarkup=()=>`
<section class="generation-console" aria-label="Generation Job Center">
  <div class="generation-heading"><div><div class="eyebrow">生成</div><h2>Job Center</h2></div><span id="generation-connector-badge" class="generation-badge">未连接</span></div>
  <div id="generation-state" class="generation-state" data-state="connection-required"><strong id="generation-state-label">Connector 未配置</strong><span id="generation-state-detail">配置本机 Connector 后才能提交或恢复生成任务。</span></div>
  <div class="generation-scroll">
    <details class="generation-section" open><summary>Connector</summary><div class="generation-section-body">
      <label>Endpoint<input id="generation-connector-endpoint" type="url" placeholder="http://127.0.0.1:PORT" /></label>
      <label>Pairing approval<input id="generation-connector-approval" type="password" autocomplete="off" spellcheck="false" placeholder="本机 sidecar approval" /></label>
      <div class="generation-inline-actions"><button id="generation-save-endpoint" type="button">保存并重载</button><button id="generation-pair" type="button">配对 / 恢复</button><button id="generation-revoke" type="button" class="danger">撤销</button></div>
      <small id="generation-pairing-hint">Pairing approval 仅用于当前配对请求，不写入 localStorage；Provider Secret 仍留在 Connector 边界。</small>
    </div></details>
    <details class="generation-section" open><summary>Provider / Capability</summary><div class="generation-section-body">
      <label>Provider<select id="generation-provider"></select></label><label>Capability<select id="generation-operation"></select></label>
      <div id="generation-capability-hint" class="generation-capability-hint">暂无可用 generation capability。</div>
      <label>Profile<input id="generation-profile" placeholder="optional profile" /></label>
      <label>Inputs JSON<textarea id="generation-inputs" rows="4" spellcheck="false">{"prompt":""}</textarea></label>
      <label>Asset ID<input id="generation-asset-id" placeholder="generated_asset_01" /></label>
      <label class="generation-confirm"><input id="generation-cost-confirm" type="checkbox" />我确认这会创建外部 Job，可能产生费用。</label>
      <button id="generation-submit" type="button" class="generation-primary">提交异步 Job</button>
      <small>这里只显示 provider 声明的 cost/duration class，不伪造价格或耗时；确认不会跨 Job 持久化。</small>
    </div></details>
    <section class="generation-section generation-jobs-section"><div class="generation-section-title"><span>Jobs</span><button id="generation-refresh" type="button">恢复 / 刷新</button></div><div id="generation-job-list" class="generation-job-list"></div></section>
    <section class="generation-section"><div class="generation-section-title"><span>Selected Job</span><small id="generation-selected-id">未选择</small></div>
      <div id="generation-job-detail" class="generation-job-detail">选择一个 Job 查看阶段、关系、Artifact 与 Admission。</div>
      <label>Compile Asset ID<input id="generation-compile-asset-id" placeholder="generated_asset_01" /></label>
      <div class="generation-inline-actions generation-job-actions"><button id="generation-job-refresh" type="button">刷新 Job</button><button id="generation-job-cancel" type="button">取消</button><button id="generation-job-import" type="button">导入 Artifact</button><button id="generation-job-compile" type="button">编译 / 注册资产</button></div>
      <div class="generation-inline-actions generation-product-actions"><button id="generation-job-spawn" type="button" disabled>加入当前世界</button><button id="generation-job-worldspec" type="button" disabled title="AS-11 后开放">用于 WorldSpec</button></div>
      <div id="generation-result-report" class="generation-result-report">Provider success 不等于 Asset ready；只有 Compiler + Admission 后才开放资产动作。</div>
    </section>
  </div>
</section>`;

export function parseGenerationInputs(value) {
  const source=String(value??'').trim(); if (!source) return {};
  let parsed; try { parsed=JSON.parse(source); } catch { throw new Error('Inputs JSON 格式无效'); }
  if (!parsed||typeof parsed!=='object'||Array.isArray(parsed)) throw new Error('Inputs JSON 必须是 object');
  return parsed;
}

export function generationStatusLabel(status) {
  return ({'generation-pending':'生成中','generation-cancelling':'取消中','provider-succeeded':'Provider 已完成','generation-failed':'生成失败','generation-cancelled':'已取消','generation-expired':'已过期','connection-required':'需要连接','generation-unknown':'未知状态'})[status]||text(status,'未知状态');
}

export function generationJobActions(job,outcome=null) {
  const providerSucceeded=job?.status==='provider-succeeded';
  const compiled=outcome?.status==='asset-ready'||outcome?.status==='asset-provisional';
  return {canRefresh:Boolean(job?.jobId),canCancel:Boolean(job?.jobId)&&ACTIVE_STATUSES.has(job.status)&&job.status!=='connection-required',canImport:Boolean(job?.jobId)&&providerSucceeded,canCompile:Boolean(job?.jobId)&&providerSucceeded,canSpawn:compiled,worldSpecEnabled:false};
}

export function capabilityHint(capability) {
  if (!capability) return '暂无可用 generation capability。';
  const duration=capability.execution?.durationClass||'unspecified', cost=capability.execution?.costClass||'unspecified';
  const connection=capability.connectionRequired?'Connector session required':'no Connector prerequisite declared';
  const auth=capability.prerequisites?.authMode||'none';
  const schema=capability.input?.schema?.id||capability.input?.schema?.title||capability.input?.types?.join(', ')||'generic input';
  const profiles=Object.keys(capability.profiles||{}); const profileText=profiles.length?` · profiles ${profiles.join(', ')}`:'';
  return `${capability.operation} · input ${schema}${profileText} · duration ${duration} · cost ${cost} · auth ${auth} · ${connection}`;
}

function el(tag,className=null,content=null){const node=document.createElement(tag);if(className)node.className=className;if(content!=null)node.textContent=String(content);return node;}
function option(value,label){const node=document.createElement('option');node.value=value;node.textContent=label;return node;}

export class GenerationJobCenter {
  constructor({root,world,tools,storage=globalThis.localStorage,locationRef=globalThis.location,log=()=>{}}={}) {
    if(!root||!world?.generation) throw new Error('GenerationJobCenter requires root and runtime generation service');
    Object.assign(this,{root,world,tools,storage,locationRef,log,jobs:[],capabilities:[],selectedJobId:null,timer:null});
    this.outcomes=new Map(); this.imports=new Map(); this.assetIds=new Map(); this.bindElements();
  }
  bindElements(){const q=(s)=>this.root.querySelector(s);this.badge=q('#generation-connector-badge');this.state=q('#generation-state');this.stateLabel=q('#generation-state-label');this.stateDetail=q('#generation-state-detail');this.endpoint=q('#generation-connector-endpoint');this.approval=q('#generation-connector-approval');this.pairingHint=q('#generation-pairing-hint');this.provider=q('#generation-provider');this.operation=q('#generation-operation');this.capabilityHint=q('#generation-capability-hint');this.profile=q('#generation-profile');this.inputs=q('#generation-inputs');this.assetId=q('#generation-asset-id');this.costConfirm=q('#generation-cost-confirm');this.jobList=q('#generation-job-list');this.selectedId=q('#generation-selected-id');this.jobDetail=q('#generation-job-detail');this.compileAssetId=q('#generation-compile-asset-id');this.resultReport=q('#generation-result-report');this.buttons={saveEndpoint:q('#generation-save-endpoint'),pair:q('#generation-pair'),revoke:q('#generation-revoke'),submit:q('#generation-submit'),refresh:q('#generation-refresh'),jobRefresh:q('#generation-job-refresh'),cancel:q('#generation-job-cancel'),import:q('#generation-job-import'),compile:q('#generation-job-compile'),spawn:q('#generation-job-spawn'),worldSpec:q('#generation-job-worldspec')};}
  async init(){
    this.endpoint.value=this.storage?.getItem?.('agentscape.connectorEndpoint')||'';
    this.buttons.saveEndpoint.addEventListener('click',()=>this.saveEndpoint());this.buttons.pair.addEventListener('click',()=>this.pair());this.buttons.revoke.addEventListener('click',()=>this.revoke());this.buttons.submit.addEventListener('click',()=>this.submit());this.buttons.refresh.addEventListener('click',()=>this.refresh({remote:true}));this.buttons.jobRefresh.addEventListener('click',()=>this.refreshSelected());this.buttons.cancel.addEventListener('click',()=>this.cancelSelected());this.buttons.import.addEventListener('click',()=>this.importSelected());this.buttons.compile.addEventListener('click',()=>this.compileSelected());this.buttons.spawn.addEventListener('click',()=>this.spawnSelected());this.provider.addEventListener('change',()=>this.renderCapabilities());this.operation.addEventListener('change',()=>this.renderCapabilityHint());this.costConfirm.addEventListener('change',()=>this.renderCapabilityHint());
    this.world.events?.on?.('generation.state',(state)=>this.renderConnectorState(state));this.world.events?.on?.('generation.job.submitted',()=>this.refresh({remote:false}));this.world.events?.on?.('generation.job.cancelled',()=>this.refresh({remote:false}));this.world.events?.on?.('generation.artifact.imported',()=>this.renderSelected());
    this.renderConnectorState(this.world.generationState||this.world.generation.connectorStatus());this.refreshCapabilities();await this.refresh({remote:this.world.generation.connectorStatus().status==='paired'});
    this.timer=setInterval(()=>{if(this.jobs.some((job)=>ACTIVE_STATUSES.has(job.status))&&this.world.generation.connectorStatus().status==='paired')this.refresh({remote:true,silent:true});},5000);return this;
  }
  destroy(){if(this.timer)clearInterval(this.timer);this.timer=null;}
  setState(state,label,detail){this.state.dataset.state=state;this.stateLabel.textContent=label;this.stateDetail.textContent=detail;}
  renderConnectorState(state={}){
    const paired=state.status==='generation-ready'||state.status==='paired';this.badge.textContent=paired?'PAIRED':'CONNECT';this.badge.classList.toggle('live',paired);
    if(paired){const connector=state.connector||this.world.generation.connectorStatus().connector;this.setState('ready','Connector 已配对',`${text(connector?.id,'Connector')} · ${text(connector?.version,'version unknown')}`);this.pairingHint.textContent='Session 已建立；Pairing approval 未持久化，Provider Secret 仍只存在于 Connector 边界。';}
    else{this.setState('connection-required','Connector 未连接',state.reason==='CONNECTOR_NOT_CONFIGURED'?'先填写 loopback Connector Endpoint。':'输入本机 Pairing approval 后建立 scoped session。');this.pairingHint.textContent='Pairing approval 仅用于当前请求，不写入 localStorage。';}
    this.buttons.revoke.disabled=!paired;this.renderCapabilityHint?.();
  }
  saveEndpoint(){const endpoint=this.endpoint.value.trim();if(endpoint)this.storage?.setItem?.('agentscape.connectorEndpoint',endpoint);else this.storage?.removeItem?.('agentscape.connectorEndpoint');this.log(endpoint?'Connector endpoint saved; reloading runtime':'Connector endpoint cleared; reloading runtime','result');this.locationRef?.reload?.();}
  async pair(){const approval=this.approval?.value?.trim()||'';try{if(!approval)throw new Error('请输入本机 Pairing approval');this.setState('working','连接中','正在与本机 Connector 建立 scoped session…');const result=await this.world.generation.pairConnector({approval});this.renderConnectorState(result);if(result.status==='generation-ready'){this.world.generationState=clone(result);this.refreshCapabilities();await this.refresh({remote:true});}}catch(error){this.setState('error','Connector 连接失败',error.message);this.log(`connector: ${error.message}`,'error');}finally{if(this.approval)this.approval.value='';}}
  async revoke(){try{const result=await this.world.generation.revokeConnector();this.world.generationState=clone(result);this.renderConnectorState(result);this.log('Connector session revoked','result');}catch(error){this.setState('error','撤销失败',error.message);this.log(`connector revoke: ${error.message}`,'error');}}
  refreshCapabilities(){const providers=this.world.generation.listGenerationProviders({availableOnly:false}).providers;this.provider.replaceChildren();for(const provider of providers)this.provider.append(option(provider.id,`${provider.displayName||provider.id} · ${provider.status}`));this.capabilities=this.world.generation.listGenerationCapabilities({availableOnly:false}).capabilities;this.renderCapabilities();}
  renderCapabilities(){const provider=this.provider.value,matching=this.capabilities.filter((capability)=>!provider||capability.provider===provider);this.operation.replaceChildren();for(const capability of matching)this.operation.append(option(capability.operation,`${capability.displayName||capability.operation} · ${capability.status}`));this.renderCapabilityHint();}
  currentCapability(){return this.capabilities.find((capability)=>capability.operation===this.operation.value)||null;}
  renderCapabilityHint(){const capability=this.currentCapability();this.capabilityHint.textContent=capabilityHint(capability);const profiles=Object.keys(capability?.profiles||{});if(profiles.length===1&&!this.profile.value.trim())this.profile.value=profiles[0];const paired=this.world.generation.connectorStatus().status==='paired';const connectionBlocked=Boolean(capability?.connectionRequired)&&!paired;this.buttons.submit.disabled=!capability||capability.status!=='available'||connectionBlocked||!this.costConfirm.checked;}
  async submit(){try{const capability=this.currentCapability();if(!capability)throw new Error('请选择 generation capability');if(!this.costConfirm.checked)throw new Error('提交前必须确认外部 Job 可能产生费用');if(capability.connectionRequired&&this.world.generation.connectorStatus().status!=='paired')throw new Error('Connector pairing is required');const assetId=this.assetId.value.trim()||`generated_${Date.now().toString(36)}`;this.buttons.submit.disabled=true;const job=await this.world.generation.submitGenerationJob({provider:capability.provider,operation:capability.operation,inputs:parseGenerationInputs(this.inputs.value),profile:this.profile.value.trim()||null,outputRoles:capability.output?.roles||[]});this.assetIds.set(job.jobId,assetId);this.selectedJobId=job.jobId;this.compileAssetId.value=assetId;this.costConfirm.checked=false;this.log(`generation submitted: ${job.jobId}${job.reused?' · reused':''}`,'result');await this.refresh({remote:false});}catch(error){this.setState('error','提交失败',error.message);this.log(`generation submit: ${error.message}`,'error');}finally{this.renderCapabilityHint();}}
  async refresh({remote=false,silent=false}={}){try{const result=remote?await this.world.generation.reconcileGenerationJobs():this.world.generation.listGenerationJobs();this.jobs=result.jobs||[];if(this.selectedJobId&&!this.jobs.some((job)=>job.jobId===this.selectedJobId))this.selectedJobId=null;if(!this.selectedJobId&&this.jobs.length)this.selectedJobId=this.jobs[0].jobId;this.renderJobs();this.renderSelected();if(!silent&&result.status==='connection-required'&&this.jobs.length)this.setState('connection-required','离线 Job 快照','Connector 不可用；显示本地 sanitized projection。');}catch(error){if(!silent){this.setState('error','Job 恢复失败',error.message);this.log(`generation refresh: ${error.message}`,'error');}}}
  renderJobs(){this.jobList.replaceChildren();for(const job of this.jobs){const button=el('button','generation-job-row');button.type='button';button.classList.toggle('selected',job.jobId===this.selectedJobId);const top=el('span','generation-job-row-top');top.append(el('strong',null,generationStatusLabel(job.status)),el('small',null,text(job.updatedAt)));const id=el('span','generation-job-row-id',job.jobId);const progress=job.progress?.value!=null?` · ${Math.round(job.progress.value*100)}%`:'';button.append(top,id,el('span','generation-job-row-meta',`${job.provider} · ${job.stage||job.phase||'pending'}${progress}`));button.addEventListener('click',()=>{this.selectedJobId=job.jobId;this.renderJobs();this.renderSelected();});this.jobList.append(button);}if(!this.jobs.length)this.jobList.append(el('div','generation-empty','暂无 Job。连接 Connector 后可恢复历史 Job。'));}
  selectedJob(){return this.jobs.find((job)=>job.jobId===this.selectedJobId)||null;}
  renderSelected(){const job=this.selectedJob(),outcome=job?this.outcomes.get(job.jobId):null,imported=job?this.imports.get(job.jobId):null,actions=generationJobActions(job,outcome);this.selectedId.textContent=job?.jobId||'未选择';this.jobDetail.replaceChildren();if(!job)this.jobDetail.append(el('div','generation-empty','选择一个 Job 查看阶段、关系、Artifact 与 Admission。'));else{for(const [label,value] of [['状态',generationStatusLabel(job.status)],['阶段',job.stage||job.phase],['Provider',job.provider],['Operation',job.operation],['Attempt',job.attempt],['Relations',(job.relations||[]).map((r)=>`${r.type}:${r.jobId}`).join(', ')||'—']]){const row=el('div','generation-detail-row');row.append(el('span',null,label),el('code',null,text(value)));this.jobDetail.append(row);}if(job.error)this.jobDetail.append(el('div','generation-error',`${text(job.error.code)} · ${text(job.error.message)}`));const artifacts=el('div','generation-artifacts');artifacts.append(el('strong',null,'Artifacts'));for(const artifact of job.artifacts||[])artifacts.append(el('div',null,`${artifact.id} · ${artifact.role} · ${artifact.mime} · ${artifact.bytes} bytes · ${artifact.hash}`));if(!(job.artifacts||[]).length)artifacts.append(el('small',null,'Provider 尚未给出 Artifact descriptor。'));this.jobDetail.append(artifacts);}const remembered=job?this.assetIds.get(job.jobId):null;if(job&&remembered&&!this.compileAssetId.value.trim())this.compileAssetId.value=remembered;this.buttons.jobRefresh.disabled=!actions.canRefresh;this.buttons.cancel.disabled=!actions.canCancel;this.buttons.import.disabled=!actions.canImport;this.buttons.compile.disabled=!actions.canCompile;this.buttons.spawn.disabled=!actions.canSpawn;this.buttons.worldSpec.disabled=true;this.renderResult(imported,outcome);}
  renderResult(imported,outcome){this.resultReport.replaceChildren();if(imported){this.resultReport.append(el('strong',null,`Artifact ${imported.artifact.integrity}`),el('div',null,`${imported.artifact.id} · ${imported.artifact.mime} · ${imported.artifact.hash}`));const lineage=imported.artifact.lineage?.parents||[];this.resultReport.append(el('small',null,`lineage parents: ${lineage.length?lineage.join(', '):'none'} · producer job: ${text(imported.artifact.producer?.jobId)}`));}if(outcome){const admission=outcome.admission||{};this.resultReport.append(el('strong',null,`${outcome.status} · admission ${text(admission.status)}`),el('div',null,`asset ${text(outcome.assetId)} · reasons ${(admission.reasons||[]).join(', ')||'none'}`));if(outcome.status==='asset-rejected')this.resultReport.append(el('div','generation-error','Provider 已成功，但 Compiler/Admission 拒绝该资产；不会提升为 asset-ready。'));}if(!imported&&!outcome)this.resultReport.append(el('div',null,'Provider success 不等于 Asset ready；只有 Compiler + Admission 后才开放资产动作。'));}
  async refreshSelected(){const job=this.selectedJob();if(!job)return;try{const updated=await this.world.generation.getGenerationJob(job.jobId),index=this.jobs.findIndex((item)=>item.jobId===job.jobId);if(index>=0)this.jobs[index]=updated;this.renderJobs();this.renderSelected();}catch(error){this.log(`generation job: ${error.message}`,'error');}}
  async cancelSelected(){const job=this.selectedJob();if(!job)return;try{await this.world.generation.cancelGenerationJob(job.jobId);await this.refresh({remote:false});}catch(error){this.log(`generation cancel: ${error.message}`,'error');}}
  async importSelected(){const job=this.selectedJob();if(!job)return;try{const result=await this.world.generation.importGenerationResult(job.jobId);this.imports.set(job.jobId,result);this.renderSelected();this.log(`artifact imported: ${result.artifact.id}`,'result');}catch(error){this.log(`artifact import: ${error.message}`,'error');}}
  async compileSelected(){const job=this.selectedJob();if(!job)return;try{const assetId=this.compileAssetId.value.trim()||this.assetIds.get(job.jobId)||`generated_${Date.now().toString(36)}`;this.assetIds.set(job.jobId,assetId);const outcome=await this.world.generation.generateAndCompileAsset({jobId:job.jobId,assetId,label:assetId});this.outcomes.set(job.jobId,outcome);const artifact=this.world.generation.artifactRegistry?.list?.().find((item)=>item.producer?.jobId===job.jobId&&item.integrity?.state==='verified');if(artifact&&!this.imports.has(job.jobId))this.imports.set(job.jobId,{status:'artifact-imported',jobId:job.jobId,artifact:{id:artifact.id,role:artifact.role,mime:artifact.mime,format:artifact.format,bytes:artifact.bytes,hash:artifact.hash,integrity:artifact.integrity?.state,producer:clone(artifact.producer),lineage:clone(artifact.lineage)},reused:true});this.renderSelected();this.log(`asset compile: ${assetId} · ${outcome.status}`,outcome.status==='asset-rejected'?'error':'result');}catch(error){this.log(`asset compile: ${error.message}`,'error');}}
  async spawnSelected(){const job=this.selectedJob();if(!job||!this.tools)return;const outcome=this.outcomes.get(job.jobId);if(!generationJobActions(job,outcome).canSpawn)return;try{const result=await this.tools.call('spawnAsset',{assetId:outcome.assetId,position:[1.5,0,1.2]});this.log(`spawn generated asset: ${outcome.assetId} · ${typeof result==='string'?'ready':'editor provisional'}`,'result');}catch(error){this.log(`spawn generated asset: ${error.message}`,'error');}}
}
